//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassiqueWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonne
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonne()
        {
            this.Achat = new HashSet<Achat>();
        }
    
        public int Code_Abonne { get; set; }
        public string Nom_Abonne { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Code_Postal { get; set; }
        public Nullable<int> Code_Pays { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Prenom_Abonne { get; set; }
    
        public virtual Pays Pays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achat> Achat { get; set; }
    }
}
