//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassiqueWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achat
    {
        public int Code_Achat { get; set; }
        public Nullable<int> Code_Enregistrement { get; set; }
        public Nullable<int> Code_Abonne { get; set; }
        public Nullable<bool> Achat_Confirme { get; set; }
    
        public virtual Abonne Abonne { get; set; }
        public virtual Enregistrement Enregistrement { get; set; }
    }
}
