//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassiqueWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Disque = new HashSet<Disque>();
        }
    
        public int Code_Album { get; set; }
        public string Titre_Album { get; set; }
        public Nullable<int> Annee_Album { get; set; }
        public Nullable<int> Code_Genre { get; set; }
        public Nullable<int> Code_Editeur { get; set; }
        public byte[] Pochette { get; set; }
        public string ASIN { get; set; }
    
        public virtual Editeur Editeur { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disque> Disque { get; set; }
    }
}
