//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassiqueWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musicien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musicien()
        {
            this.Composer = new HashSet<Composer>();
            this.Direction = new HashSet<Direction>();
            this.Interpreter = new HashSet<Interpreter>();
        }
    
        public int Code_Musicien { get; set; }
        public string Nom_Musicien { get; set; }
        public string Prenom_Musicien { get; set; }
        public Nullable<int> Annee_Naissance { get; set; }
        public Nullable<int> Annee_Mort { get; set; }
        public Nullable<int> Code_Pays { get; set; }
        public Nullable<int> Code_Genre { get; set; }
        public Nullable<int> Code_Instrument { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composer> Composer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direction> Direction { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Instrument Instrument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interpreter> Interpreter { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
